---
apiVersion: v1
kind: Service
metadata:
  name: ci-demo-application
  labels:
    name: ci-demo-application
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: ci-demo-application